conda activate torch112
CUDA_VISIBLE_DEVICES=4 python csn_main_train.py \
 --msg_len 4 \
 --data data/CodeSearchNet \
 --lang java \
 --batch_size 80  \
 --epochs 200 \
 --save csn_java_full \
 --resume csn_java_noft \
 --optimizer adam \
 --use_reconst_loss \
 --use_semantic_loss \
 --sem_weight 6 \
 --use_lm_loss \
 --lm_weight 1.3 \
 --lm_ckpt csn_lm.pt \
 --discr_interval 3 \
 --msg_weight 6 \
 --gen_weight 1 \
 --reconst_weight 2 \
 --scheduler \
 --shared_encoder 1 \
 --allow_cached_dataset \
 --train_subsample_num 36000 \
 --eval_subsample_num 8000 \
