conda activate torch112
CUDA_VISIBLE_DEVICES=5 python cwm_main_train.py \
 --msg_len 4 \
 --data ~/code-watermarking/data/github_c \
 --lang c \
 --batch_size 24  \
 --epochs 100 \
 --save github_c_full \
 --resume github_c \
 --optimizer adam \
 --use_reconst_loss \
 --use_semantic_loss \
 --sem_weight 6 \
 --use_lm_loss \
 --lm_weight 6 \
 --lm_ckpt github_c_lm.pt \
 --discr_interval 3 \
 --msg_weight 6 \
 --gen_weight 1 \
 --reconst_weight 2 \
 --scheduler \
 --shared_encoder 1 \
